### PR TITLE
A lot of additions :)

### PR DESCRIPTION
**Pull request by goosedb**
Now tan can be called also with 'tg'.  ctg, asin, acos. Constans Pi and E also were added.

### CODE REVIEW

**Comment by z2oh** [comment]
Hey @GooseDB , thanks for your contribution!

Two things with your implementation of constants:

* Euler's number is a built-in constant like pi: https://doc.rust-lang.org/beta/std/f64/consts/constant.E.html prefer this over generating it using `exp()`
* Constants are parsed before variables are read, which causes `ex` to be parsed as `E * x`, with e being parsed as the constant. `ex` should be parsed as a single variable `ex`. See #22

**Comment by goosedb** [comment]
@z2oh 
> ex should be parsed as a single variable ex.

Why?

**Comment by z2oh** [comment]
I plan on using this parser for more general applications that just plotting a function with a hardcoded variable `x`. Eventually, I want to allow for more variable names, including multi-character variables.

Imagine if, in a Rust program, you could not name a variable `letter` because it started with `let`. That would get annoying quickly! Variables should be able to have arbitrary names, as long as they don't match another reserved word _exactly_ i.e. `tan`, `e`, and `pi` are invalid variable names (they are reserved), but `tanner`, `ex`, and `pip` should be parsed as single variable names.

That's why adding constants is harder than it first seemed! :)

**Comment by goosedb** [comment]
Ok, I've got it. Give me time.

**Comment by goosedb** [comment]
So, what about this, bro? :)

**Comment by z2oh** [comment]
Alright looks good! Thanks @GooseDB !

**Pull request merged**
