### PR TITLE
Display active input

### PR DESCRIPTION
**Pull request by ajcpwnz**

### CODE REVIEW

**Comment by ajcpwnz** [comment]
@z2oh I've simplified comparison per comment in #3. Regarding the colors, you think i should leave border color unchanged or I misunderstood?

**Comment by z2oh** [comment]
This is awesome! ~~Let's "oxidize" your code a bit :)~~

The `input_style` and `border_style` methods would be a bit more clear if they were named `get_input_style` and `get_border_style`. This is more subjective, but I prefer typing a few extra characters for the increased clarity it provides.

~~You pass around `&str` (string literals) to the function and then match on them to figure out which enum variant of `SelectedBox` you have. This is perfectly fine (it works after all!) but since we are already using enums, let's really take advantage of that! Instead of passing `"function"` for example, you can pass `SelectedBox::Function` directly! Then you can change your method to accept a `SelectedBox` instead of a `&str`.~~

~~Like this:~~

```
fn get_input_style(&self, input_box: SelectedBox) -> Style {
    ...
}
```

~~Then you can just see if `input_box` is equal to `self.selected_box` and you cut out a few lines of code! (Note: this will require the use of https://doc.rust-lang.org/std/cmp/trait.PartialEq.html which overloads the `==` operator, but Rust can auto-derive this on enum types using `#[derive(PartialEq)]`)~~

_I just saw e1fdd95, you're way ahead of me! :)_

In regards to the color choice: my terminal displays text as black on a white background, so when magenta is used the text is hard to read (black is close to magenta). However, after playing around with it a bit I was thinking we may not need the background highlighting at all: maybe just having the border around the currently selected box is enough? What do you think? Otherwise, if we can figure out a way to style the text differently so that we can ensure it is readable, that would be good too. If we stick with the background color, I'd like to have the same background color for the border pieces. What do you think about that?

**Comment by ajcpwnz** [comment]
@z2oh I really like the idea of changing just the border color for overall simplicity.
However (mentioning this for future reference), adding `.fg(<Color>)` call inside `input_style` would change the text color inside the active box.

**Comment by z2oh** [comment]
Okay cool! It's worth keeping in mind for playing around with the styling more later. It would be neat to for example: highlight all instances of `x` in the function string to make it easier to visually parse. Like syntax highlighting!

I may be getting too far ahead of myself though :)

**Comment by ajcpwnz** [comment]
@z2oh What really has to be considered, is how different user preferences should be treated. Since they can have any possible configuration, `MAGENTA` can equal `WHITE` for example and active input won't be distinguishable. I guess setting colors in rgb helps, but then all colors should be set explicitly. 

_This is probably a subject for another discussion/issue (say 'figure color scheme') as it's not directly related to the subject of PR._

**Comment by z2oh** [comment]
Would you mind making an issue for it? We can continue discussion of colors/theming there.

**Pull request merged**
